name = "DT47 Servers Pack"
author = "MetalBox47"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "968db124fbd035c242053a4aeb41cb5ae44a34bca0370bfdd056bb22f39a7d72"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
