name = "DT47 Servers Pack - 1.21.1 Edition"
author = "MetalBox47"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7778ef8bb04ed7a85eaf6e02d01826b3c05eb0bd1870434227150d43a40b7cca"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.234"
